import SignupModal from "@/components/signupModal";
import { Heading } from "@chakra-ui/react";
import Head from "next/head";


export default function Home() {
  return (
    <>
      <Head>
        <title>Home Interior</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading>home</Heading>
      <SignupModal/>
    </>
  );
}
